### ISSUE TITLE
Meeting time for next week?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/next-10#8]
Last week our meeting was at 7am PST, in the calendar it's showing the same time for next week. We discussed using the TSC rotation, which would mean next week the meeting would be at 1pm PST. I just want to double check if the meeting next week will be at 7am or 1pm PST. Also, I noticed the event doesn't repeat (next week is the last one), is that intentional so we evaluate after each meeting if we should keep having those?

**Comment by mhdawson** [comment]
@mmarchini  Because of the rotation and other community meetings I had to use the same slot for this meeting, the others either conflicted with the TSC meeting or another already scheduled Node.js community meeting. 

I've not scheduled it ongoing as I've not had time to figure out a rotation that will avoid those conflicts, happy to have somebody else to do that and add the entries to the calendar, or even just figure it out and tell me what recurring entries to add to the calendar as the adding part is easy.

**Comment by mmarchini** [comment]
Ah I see, thanks for the context!

**Comment by mhdawson** [comment]
np, I probably should have metioned it somewhere.

**Comment by mhdawson** [comment]
I've set the best schedule I could find without conflicts for the next little while. Next meeting is Thursday Aug 20 at 5 EST: https://github.com/nodejs/next-10/issues/12

**Comment by mhdawson** [comment]
closing
